const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.solid,
		C3.Plugins.shadowlight,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.shadowlight.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.shadowlight.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Exps.Count
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{ScrollTo: 0},
	{MoveTo: 0},
	{Player: 0},
	{ShadowCaster: 0},
	{Solid: 0},
	{Wall: 0},
	{ShadowLight: 0},
	{ActiveCellMarker: 0},
	{TiledBackground: 0},
	{ClueSlot: 0},
	{IsFindable: 0},
	{IsClueFound: 0},
	{Tween: 0},
	{Item: 0},
	{ItemPlace: 0},
	{PlacedItems: 0},
	{Touch: 0},
	{ItemPlaces: 0},
	{ClueContainer: 0},
	{ClueText: 0},
	{WinBackground: 0},
	{WinText: 0},
	{GRID_SIZE: 0},
	{NUMBER_OF_ITEMS: 0},
	{NumberOfItemsFound: 0},
	{OverlappedItemFrame: 0},
	{Frame: 0},
	{ItemPlaceUID: 0},
	{ItemUID: 0},
	{FadeIn: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	ActiveCellMarker: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Item: class extends self.ISpriteInstance {},
	ItemPlace: class extends self.ISpriteInstance {},
	PlacedItems: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	ItemPlaces: class extends self.IArrayInstance {},
	ClueContainer: class extends self.IWorldInstance {},
	ClueText: class extends self.ITextInstance {},
	WinBackground: class extends self.IWorldInstance {},
	WinText: class extends self.ITextInstance {}
}